name: Github Action for LaTeX
on: [push]
jobs:
  compile-card-tex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v3
        with:
          # The root LaTeX file to be compiled
          root_file: card.tex
          latexmk_use_xelatex: true

      - uses: MaineK00n/latex-actions@v0.0.1
        with:
          root: card.tex
          pdf_name: businesscard
